# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUMZUDQyP-2wiVEA7JP0UCde5SyDZLa4
"""

# salomlashish_va_qiziqishlar.py

def salomlashish(ism, qiziqishlar):
    print(f"Salom, {ism}!")
    print(f"Sizning qiziqishlaringiz: {', '.join(qiziqishlar)}")
    print("Ajoyib, men ham!")

# Foydalanuvchidan ism va qiziqishlarini olish
ism = input("Ismingizni kiriting: ")
qiziqishlar_str = input("Qiziqishlaringizni vergul bilan ajrating (masalan: sport, musiqa, o'qish): ")

# Qiziqishlarni ro'yxatga aylantirish
qiziqishlar = qiziqishlar_str.split(', ')

# Funksiyani chaqirish
salomlashish(ism, qiziqishlar)